import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import { VitePWA } from 'vite-plugin-pwa';

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    VitePWA({
      registerType: 'autoUpdate',         // SW auto-updates in background
      injectRegister: 'auto',
      includeAssets: ['favicon.svg', 'icons/*.png', 'AvatarWelcome.webp', 'HopeFinal.webp'],
      manifest: {
        name: 'Mynzo – Shop Smarter',
        short_name: 'Mynzo',
        description: "India's smartest shopping app – crazy deals, gifting & more",
        start_url: '/',
        display: 'standalone',
        background_color: '#ffffff',
        theme_color: '#ee4923',
        icons: [
          { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any maskable' },
          { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any maskable' },
        ],
        shortcuts: [
          { name: 'Crazy Deals', url: '/crazy-deals', description: 'View today\'s crazy deals' },
          { name: 'My Cart',     url: '/cart',         description: 'View your cart' },
        ],
      },
      workbox: {
        // Precache all JS, CSS and HTML generated by Vite
        globPatterns: ['**/*.{js,css,html,ico,svg,woff2}'],
        // Runtime caching rules
        runtimeCaching: [
          {
            // Uploaded product/banner/category images → cache for 7 days
            urlPattern: /\/uploads\//,
            handler: 'CacheFirst',
            options: {
              cacheName: 'mynzo-uploads',
              expiration: { maxEntries: 200, maxAgeSeconds: 60 * 60 * 24 * 7 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
          {
            // Public static assets (webp images, mp4 splash)
            urlPattern: /\.(webp|png|jpg|jpeg|mp4|svg)$/,
            handler: 'CacheFirst',
            options: {
              cacheName: 'mynzo-assets',
              expiration: { maxEntries: 100, maxAgeSeconds: 60 * 60 * 24 * 7 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
          {
            // API catalog endpoints → show cached, refresh in background
            urlPattern: /\/admin\/catalog\//,
            handler: 'StaleWhileRevalidate',
            options: {
              cacheName: 'mynzo-api-catalog',
              expiration: { maxEntries: 20, maxAgeSeconds: 60 * 10 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
          {
            // Google Fonts → cache for 1 year
            urlPattern: /^https:\/\/fonts\.(?:googleapis|gstatic)\.com\/.*/,
            handler: 'CacheFirst',
            options: {
              cacheName: 'google-fonts',
              expiration: { maxEntries: 10, maxAgeSeconds: 60 * 60 * 24 * 365 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
        ],
      },
      devOptions: {
        enabled: false,   // Don't activate SW in dev (avoids stale cache confusion)
      },
    }),
  ],

  server: { host: true },

  build: {
    target: 'esnext',           // Modern output — smaller, faster
    minify: 'esbuild',          // Fast + effective minification
    rollupOptions: {
      output: {
        // Split large vendor libs into separately cached chunks
        manualChunks: {
          'react-vendor':   ['react', 'react-dom', 'react-router-dom'],
          'ui-vendor':      ['framer-motion', 'lottie-react', 'lucide-react'],
          'pinch-vendor':   ['react-zoom-pan-pinch'],
        },
      },
    },
    // Warn if any single chunk exceeds 800 kB (helps catch bundle bloat)
    chunkSizeWarningLimit: 800,
  },
});